sudo: required
services:
  - docker

before_install:
  - docker build -t kaitlinsickles/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kaitlinsickles/react-test npm test

after_success:
  - docker build -t zksickles/multi-client ./client
  - docker build -t zksickles/multi-nginx ./nginx
  - docker build -t zksickles/multi-server ./server
  - docker build -t zksickles/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take those images and push them to docker hub
  - docker push zksickles/multi-client
  - docker push zksickles/multi-nginx
  - docker push zksickles/multi-server
  - docker push zksickles/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket-name: elasticbeanstalk-us-east-1-694730316680
  bucket-path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY